### ISSUE TITLE
Logster does not process lines on first call with new file

### ISSUE THREAD

**Issue by alastic** [etsy/logster#75]
I create a file, call it "logfile" with just 3 lines in it. "ParserLogster.py" contains nothing but a print(line) in parse_line().

Running 
logster --output=stdout ParserLogster logfile
Does not produce any output the first time. Running it again prints out all the lines.

**Comment by fbm-static** [comment]
Hello,

I am trying to make a parser and I was wondering if there's an argument I could pass to go into "testing" mode? The parse_line has stopped from being called and I think it might be because of a state file somewhere. I tried deleing `/var/run/logtail-myparser.CustomParsertest.log.state` but it still doesn't call parse_line. I think I may have missed something.
